
site_name: GCES 2023.1 - SIGeD

repo_name: '2023-1-GCES-SIGeD/2023-1-GCES-SIGeD-Documentacao'
repo_url: 'https://github.com/2023-1-GCES-SIGeD/2023-1-GCES-SIGeD-Documentacao'

nav:
  - Home: 
    - GCES 2023.1 - SIGeD: index.md
  - Sprint 1: sprint1.md
  - Sprint 2: sprint2.md
  - Sprint 3: sprint3.md
  - Atas de Reuniões: 
    - Reunião em 26/04/2023: ataReuniao260423.md

theme:
  name: "material"
  font:
    text: Mulish
  palette:
    primary: "indigo"
    accent: "green"
  language: pt
  logo: images/Icon.png
  favicon: images/Icon.png
  icon:
    repo: fontawesome/brands/github


  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    #- navigation.expand
    #- navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/2023-1-GCES-SIGeD/2023-1-GCES-SIGeD-Documentacao

# plugins:
#   - search
#   - awesome-pages

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      options:
        custom_icons:
          - overrides/.icons
